GET http://localhost:3000/user-api/users


###
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id":100,
    "name":"charan",
    "age":19
}


###
PUT http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id":100,
    "name":"sai",
    "age":22
}

###
DELETE http://localhost:3000/user-api/users/100

###
GET http://localhost:3000/user-api/users/100






###
GET  http://localhost:3000/product-api/products

###
GET  http://localhost:3000/product-api/products/product-id/200

###
GET  http://localhost:3000/product-api/products/product-brand/HP


###
POST  http://localhost:3000/product-api/products
Content-Type: application/json

{
    "productId":200,
    "name":"keyboard",
    "price":1500,
    "brand":"HP"

}



###
PUT  http://localhost:3000/product-api/products/200
Content-Type: application/json

{
    "productId":200,
    "name":"keyboard",
    "price":2500,
    "brand":"HP"
}


###
DELETE  http://localhost:3000/product-api/products/200



