### read all users

GET http://localhost:4000/user-api/users


### read user by objectid
GET http://localhost:4000/user-api/users/697dbb7903b47c14944901f8

###create user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username":"akash",
    "password":"bhanu",
    "age":20
}

### update user

PUT http://localhost:4000/user-api/users/697dbd11065c60c4ecd67cc9
Content-Type: application/json

{
    "username":"charan",
    "password":"reddy",
    "age":20
}


### delete user

PUT http://localhost:4000/user-api/users/697dbd11065c60c4ecd67cc9



### get products 
GET http://localhost:4000/product-api/products
### get product by id
GET http://localhost:4000/product-api/products/697f6acbc9c79b4184137d6d

###create product
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "pid":24,
    "pname":"laptop",
    "price":45000
}

### update product put
PUT http://localhost:4000/product-api/products/697f6acbc9c79b4184137d6d
Content-Type: application/json

{
    "pid":23,
    "pname":"phone",
    "price":25000
}

### delete product 
DELETE http://localhost:4000/product-api/products/697f6acbc9c79b4184137d6d